\subsection{Biology of Cholera}
Although it is listed as one of the oldest known diseases, cholera remains a major public health concern in areas with poor water sanitation with an estimated 1.3-4 million cases every year \citep{link18}.
Cholera is an infectious disease caused by the bacterium \textit{Vibrio cholerae}.
The bacterium survives and reproduces in aquatic environments, and is capable of colonizing small intestines \citep{link8}.
The disease is not airborne, but can be transmitted through contaminated food or water and can survive in some aquatic environments from months to years \citep{link9}.
The bacterium produces enterotoxins responsible for the symptoms of cholera infection which are severe diarrhea, vomiting and nausea \citep{link11}.
%Approximately only one in ten people infected develop symptoms, and if not treated urgently, these symptoms can lead to severe dehydration.
Dehydration thickens the blood, causing circulation problems that can lead to death within a few hours.
Since dehydration is the main problem, rehydration with clean water and minerals (such as ORS packages) is the most effective treatment \citep{link18}.
Current improvements in public health and sanitation largely decrease the likelihood of a cholera outbreak \citep{link18}.\par
Four major outbreaks of cholera in the 19th century devastated the London population, resulting in tens of thousands of deaths.
One of the early theories believed to be the cause of spread of cholera was the Miasma theory, suggesting that cholera is an airborne disease and that impurities in the air induced the spread \citep{link1}.
Thus, the suggested solution in 1848 was to discard the contents of cesspools and raw sewage pits into the River Thames.
Since Thames was the drinking source of many, the misunderstanding about the method of transmission resulted in heightened number of infected individuals, severely worsening the epidemic \citep{link1}.
Early studies on cholera, such as the work of Jon Snow in the mid 19th century, have been pivotal in the development of modern epidemiology.
However, the abundance of more recent studies using mathematical frameworks that try to model a framework for anticipating outbreaks of cholera and planning for interventions is the reason for our focus on this particular disease.
\subsection{Transmission Dynamics of Cholera}
Before introducing a simple model to simulate the temporal spread of cholera, we must discuss the processes we plan to analyze.
The model should include the entire population, which for simplicity we will assume is comprised of only three groups: the susceptible, the infected (or infectious), and the recovered.
The only area still remaining that has a major impact on the epidemic is the environment, or in this case the water.
We assume that only Infectious individuals can contaminate the water sources by shedding the pathogen into the water.
The halting remedy suggested increased the rate of water contamination drastically, which in turn increased the transmission rate from individuals coming into contact with the infected water.
This is a plausible explanation for why maximum weekly deaths in London increase more than two-fold in the 1848 epidemic compared to the 1832 epidemic \citep{link3}.
The main treatment strategies for cholera outbreaks are vaccination, antibiotic treatment, and water sanitation.
We can incorporate these into our model to simulate the effect that each of these strategies has on the disease dynamics.
\subsection{SIRW Model Construction}
Our model has four distinct departments: susceptible, infectious, recovered, and water compartments \citep{link9}.
Susceptible: The proportion of the population that is susceptible to being infected by cholera.
Newborns are directly added to S at a rate $\mu$.
Individuals leave this compartment in one of two ways. They either die at a rate $\mu$, or come into contact with the pathogen and move into the “Infectious” compartment. Our model assumes equal rates of natural birth and death.
Interactions of susceptible and infectious individuals from the I compartment yields new infected individuals at a rate of $\beta_I$, and interactions of susceptible individuals with the water compartment W yields new infected individuals at a rate $\beta_w$.\par
Infectious (infected): The proportion of individuals that have been infected with cholera.
Individuals in this compartment are capable of infecting susceptible individuals during interactions at a rate of $\beta_i$.
They are also capable of contributing to the choleric load of the water compartment by “shedding” the pathogen at a rate $\xi$. 
Although for cholera the rate of transmission from person to person interactions is much lower in reality than the rate of transmission through contact with infected waters, we decided it still has enough significance to be in the model.
Individuals in this compartment recover at a rate $\gamma$, and move to the recovered compartment, or they die naturally (not from Cholera) at a rate $\mu$ and from Cholera at a rate $\alpha$. 
With advances in medicine over the past decades $\alpha$ is no longer a significant parameter in todays world.\par
Recovered: The proportion of individuals that are neither infected with cholera or susceptible to the pathogen.
They leave this compartment as they die naturally at a rate $\mu$.
Water: The W term is proportional to the concentration of Cholera in the environment (or in this case the water).
More bacteria enter the compartment as infected individuals shed the pathogen at a rate $\xi$, and the pathogen dies at a rate $\sigma$.
