% !Rnw root = main.Rnw
%{\Large London Influenza Time Series}\\
<<London, echo=FALSE, cache=FALSE>>=
source('./measles.R')
londf <- read.ymdc('./meas_uk__lon_1944-94_wk.csv')
lonwidths <- c(0.51,0.35,0.14)
multipanel(df,lonwidths)
@
%{\Large Liverpool Influenza Time Series}
<<Liverpool, echo=FALSE, cache=FALSE>>=
lpldf <- read.ymdc('./meas_uk__lpl_1944-94_wk.csv')
lplwidths <- c(0.45,0.25,.30)
multipanel(lpldf,lplwidths)
@
